on: [push]

jobs:
  generate_md_files_job:
    runs-on: ubuntu-latest
    name: Generate MD files
    steps:
      # Generates the MD files with the action
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate MD files Step
        uses: Keenan-Tisch/json-schema-md-doc@master
        id: generate_file
      # commits the updated MD files
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
